import dynamicProgramming.Fibona.fibo1
import dynamicProgramming.Fibona.fibo2
import dynamicProgramming.LongestPalindrome.longestPalindrome
import dynamicProgramming.LongestPalindrome.longestPalindrome2
import dynamicProgramming.LongestPalindrome.longestPalindrome3
import dynamicProgramming.LongestPalindrome.longestPalindromeDynamic
import dynamicProgramming.MaxArray
import dynamicProgramming.PascalTrigle.generate
import dynamicProgramming.PascalTrigle.pascalTrigleAtposition

fun main(args: Array<String>) {
    val nums = intArrayOf(-2, 1, -3, 4, -1, 2, 1, -5, 4)
    val nums2 = intArrayOf(5,4,-1,7,8)

//    println(longestPalindrome("babad"))
//    println(longestPalindromeDynamic("civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth"))
//    println(MaxArray.maxSubArray(nums2))

//    fibo2(25)
    generate(3)

//    println("${pascalTrigleAtposition(3)}")
}
